"""
Sync Schemas — Offline-first batch sync request/response contracts
"""

from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from datetime import datetime


class SyncEvent(BaseModel):
    """A single event generated by the mobile client while offline."""
    event_id: str  # Client-generated unique ID (deduplication key)
    type: str  # CHECKPOINT_CONFIRMED, EVIDENCE_CAPTURED, DRIVER_LOCATION, etc.
    client_timestamp: str  # ISO 8601 timestamp when event was created on device
    data: Dict[str, Any]  # Event-specific payload


class BatchSyncRequest(BaseModel):
    """Batch of offline events sent from mobile client on reconnection."""
    device_id: str
    events: List[SyncEvent]
    last_sync_at: Optional[str] = None  # ISO timestamp of last successful sync


class EventResult(BaseModel):
    """Result for a single processed event."""
    event_id: str
    status: str  # success, failed, duplicate, conflict
    server_id: Optional[int] = None  # Server-assigned ID if created
    error: Optional[str] = None


class ServerUpdate(BaseModel):
    """A server-side update to push back to the client."""
    resource_type: str  # shipment, checkpoint, alert, etc.
    resource_id: int
    action: str  # created, updated, deleted
    data: Dict[str, Any]
    updated_at: str


class BatchSyncResponse(BaseModel):
    """Response returned after processing a batch sync."""
    processed: int
    success_count: int
    failed_count: int
    conflict_count: int = 0
    results: List[EventResult]
    server_updates: List[ServerUpdate] = []
    sync_timestamp: str = ""

    def __init__(self, **data):
        if "sync_timestamp" not in data or not data["sync_timestamp"]:
            data["sync_timestamp"] = datetime.utcnow().isoformat() + "Z"
        super().__init__(**data)
